### ISSUE TITLE
/blocks/transaction endpoint is not working

### ISSUE THREAD

**Issue by PrernaPadhee** [oasisprotocol/oasis-rosetta-gateway#342] opened 2022-05-11 11:19 UTC
I am unable to fetch transaction details. I am using the following API call :
curl --location --request POST '10.213.67.9:8080/block/transaction'
--header 'Content-Type: application/json'
--data-raw '{
"network_identifier": {
"blockchain": "Oasis",
"network": "b11b369e0da5bb230b220127f5e7b242d385ef8c6f54906243f30af63c815535"
},
"block_identifier": {
"index": 8486594,
"hash": "ff9e6322a6c10a09fafbd2a53a5b9a8eb86776fe3e7f850fcf8a4f0e88bce5f4"
},
"transaction_identifier": {
"hash": "092af6d5f43f1107bee6e91ae2bfac38e1805507bd841f1b791c6631e80219ba"
}
}'

and the response i get is as follows:

{
"code": 13,
"message": "operation not implemented",
"retriable": false
}

I have tried to run other api calls against my node and all of them work fine. For example : /block and /accoount/balance

Can you confirm if the /block/transaction endpoint is available or not for fetching transaction details?

**Comment by pro-wh** [comment] 2022-05-11 17:55
Confirming the contrary, that it is not available. Use /blocks to get transaction details.

**Comment by PrernaPadhee** [comment] 2022-05-12 12:20
> Confirming that it is not available. Use /blocks to get transaction details.

Can you let  us know if this implementation is in the pipeline and is intended for future releases or not ?

**Comment by pro-wh** [comment] 2022-05-12 23:30
That's the nature of Rosetta's API. The only details that are exposed are balance changes. Incidentally, for some staking related transactions, there will be operations listed. However, the Oasis consensus layer mostly serves to confirm paratime state changes, which doesn't involve consensus layer staking balance changes. You should expect to see a lot of "roothash" transactions with no operations in the Rosetta representation, and those will really be the full Rosetta transaction with all the intended details. The /block/transaction endpoint, though not implemented, would not give any additional details.

There is no ongoing work to implement /block/transaction.

**Comment by pro-wh** [comment] 2022-05-12 23:34
let's close this as a duplicate of #82.

requesting /block/transaction be implemented would be a valid new issue. but be aware that it would also correctly report `"operations: []` for transactions that do not affect balances, and there would be no additional details available from it. it's not indicated that the reporter really wants that

**Closed by pro-wh** 2022-05-12 23:34 UTC

**Comment by PrernaPadhee** [comment] 2022-05-16 05:51
> let's close this as a duplicate of #82.
> 
> requesting /block/transaction be implemented would be a valid new issue. but be aware that it would also correctly report `"operations: []` for transactions that do not affect balances, and there would be no additional details available from it. it's not indicated that the reporter really wants that

Can you confirm the transaction types that will affect balances for which the operations data is expected in /block response?

**Comment by pro-wh** [comment] 2022-05-16 18:23
you might be able to determine that by analyzing the oasis-core codebase, but it'll be less maintenance work to look at staking events instead. would that work for you?

**Comment by PrernaPadhee** [comment] 2022-05-19 12:36
> you might be able to determine that by analyzing the oasis-core codebase, but it'll be less maintenance work to look at staking events instead. would that work for you?

so do we get operation information for all staking events in the /block response?

**Comment by pro-wh** [comment] 2022-05-19 18:30
no. notably, when debonding begins, there is no change in the rosetta accounts model, so there are no operations. not sure if there's metadata for it though
